apiVersion: v1
kind: Service
metadata:
  name: ecom-api
  namespace: ecom
  labels:
    app.kubernetes.io/name: ecom-api
    app.kubernetes.io/part-of: sre-final
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ecom-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
